backend:
  name: git-gateway
  branch: main

media_folder: "imagenes"
public_folder: "/imagenes"

collections:
  - name: "gallery"
    label: "Galería"
    label_singular: "Imagen"
    file: "_data/gallery.json" # El archivo único que contendrá la lista de imágenes
    fields:
      - name: "images" # Este campo contendrá la lista de imágenes
        label: "Imágenes"
        widget: "list"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Imagen", name: "image", widget: "image" }
          - { label: "Descripción", name: "description", widget: "text" }