backend:
  name: git-gateway
  branch: main

media_folder: "imagenes"
public_folder: "/imagenes"

collections:
  - name: "atrapasuenios"
    label: "Atrapasueños"
    label_singular: "atrapasueños"
    file: "_data/atrapasuenios.json" # Cambiado de 'folder' a 'file'
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Descripción", name: "description", widget: "text" }
