backend:
  name: test-repo

media_folder: "imagenes"
public_folder: "/imagenes"

collections:
  - name: "galeria"
    label: "Galería"
    folder: "galeria"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Imagen", name: "imagen", widget: "image" }
      - { label: "Descripción", name: "descripcion", widget: "text" }
