backend:
  name: git-gateway
  branch: main

media_folder: "imagenes"
public_folder: "/imagenes"

collections:
  - name: "galeria"
    label: "Galería"
    folder: "galeria"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "imagen", label: "Imagen", widget: "image" }
      - { name: "descripcion", label: "Descripción", widget: "text" }
